### ISSUE TITLE
在mac下 heic图片不支持

### ISSUE THREAD

**Issue by J2zl** [meetqy/rao-pics#239]
<img width="213" alt="image" src="https://github.com/rao-pics/core/assets/23160330/30d57bae-f3d8-4c56-abae-544959e62811">

**Comment by meetqy** [comment]
可以提供一张 heic 格式的图片吗，不知道在哪里可以下载到。

**Comment by J2zl** [comment]
> 

[https://black-hat.cn/static/img/2153816053132558336.heic](url)

**Comment by J2zl** [comment]
> 可以提供一张 heic 格式的图片吗，不知道在哪里可以下载到。

[https://black-hat.cn/static/img/2153816053132558336.heic](https://github.com/rao-pics/core/issues/url)
